# Codecov Configuration
# https://docs.codecov.com/docs/codecovyml-reference

coverage:
  precision: 2
  round: down
  range: "40...80"

  status:
    project:
      default:
        target: 50%
        threshold: 5%
        if_ci_failed: error
    patch:
      default:
        target: 60%
        threshold: 10%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

flags:
  unittests:
    paths:
      - src/
    carryforward: true
  integration:
    paths:
      - tests/
    carryforward: true

ignore:
  - "examples/**/*"
  - "benches/**/*"
  - "tests/**/*"
  - "**/*_test.rs"
  - "**/tests.rs"
